wandb_version: 1

dataset:
  desc: null
  value: IamLinesDataset
experiment_group:
  desc: null
  value: null
gpu_ind:
  desc: null
  value: 2
model:
  desc: null
  value: LineModelCtc
network:
  desc: null
  value: line_lstm_ctc
network_args:
  desc: null
  value:
    lstm_layers: 2
    window_stride: 2
train_args:
  desc: null
  value:
    batch_size: 64
    epochs: 64
