wandb_version: 1

dataset:
  desc: null
  value: IamLinesDataset
experiment_group:
  desc: null
  value: null
gpu_ind:
  desc: null
  value: 0
model:
  desc: null
  value: LineModelCtc
network:
  desc: null
  value: line_lstm_ctc
network_args:
  desc: null
  value:
    window_stride: 2
    window_width: 6
train_args:
  desc: null
  value:
    batch_size: 32
    epochs: 64
    user_name: hoktay
